Repository knative/specs, pull requests merged in 2021-09, with the labels that each got.

#35 Adjust OWNERS per @duglin
  OWNERS
Labels: cla: yes, size/XS, lgtm, approved

#34 Fix OWNERS file
  OWNERS
Labels: cla: yes, size/XS, lgtm, approved

#41 Adding note on immutable broker.spec.config
  specs/eventing/control-plane.md
Labels: cla: yes, size/XS, lgtm, approved

#55 fix link to data-plane event delivery
  specs/eventing/control-plane.md
Labels: cla: yes, size/XS, lgtm, kind/bug, approved

#30 Require that spec.subscriber is set for Subscription.
  specs/eventing/control-plane.md
Labels: cla: yes, size/S, lgtm, approved

#63 Fix "Channel" link in Control Plane Contract
  specs/eventing/control-plane.md
Labels: cla: yes, size/XS, lgtm, approved

#26 Minor readability updates to serving overview doc
  specs/serving/overview.md
Labels: cla: yes, kind/documentation, lgtm, size/M, approved

#65 Add sub-OWNERS for test_plans
  test-plan/OWNERS
Labels: cla: yes, size/XS, lgtm, approved

#72 not all volume mounts are readonly
  specs/serving/knative-api-specification-1.0.md
Labels: cla: yes, size/XS, lgtm, approved, needs-TMC-review

#70 TrafficTarget.percent should be REQUIRED
  specs/serving/knative-api-specification-1.0.md
Labels: cla: yes, size/XS, lgtm, approved, needs-TMC-review

#68 drop logURL requirement
  specs/serving/knative-api-specification-1.0.md
Labels: cla: yes, size/XS, lgtm, approved, needs-TMC-review

#69 drop deprecated Revision.Status.imageDigest
  specs/serving/knative-api-specification-1.0.md
Labels: cla: yes, size/S, lgtm, approved, needs-TMC-review

#61 Clarify the type and format of ` lastTransitionTime` fields
  specs/common/error-signalling.md
Labels: cla: yes, size/XS, kind/api-change, kind/enhancement, lgtm, approved, needs-TMC-review

#71 [RECOMMENDED] introduce actualReplicas & desiredReplicas
  specs/serving/knative-api-specification-1.0.md
Labels: cla: yes, size/S, lgtm, approved, needs-TMC-review

#33 Allow max #containers to be larger than 1
  specs/serving/knative-api-specification-1.0.md
Labels: cla: yes, size/XS, lgtm, approved, needs-TMC-review

#74 Broker Lifecycle conformance test plan proposal
  test-plan/eventing/README.md
  test-plan/eventing/broker-lifecycle-conformance.md
  test-plan/eventing/control-plane/broker-lifecycle/broker.yaml
  test-plan/eventing/control-plane/broker-lifecycle/trigger-no-broker.yaml
  test-plan/eventing/control-plane/broker-lifecycle/trigger.yaml
Labels: cla: yes, kind/enhancement, lgtm, size/L, approved

#78 added links for tests implementation in eventing for Brokers tests plan
  test-plan/eventing/broker-lifecycle-conformance.md
Labels: cla: yes, size/S, lgtm, approved
