Repository knative/specs, pull requests merged in 2021-03, with the labels that each got.

#5 Copy specs from knative/eventing
  specs/README.md
  specs/eventing/README.md
  specs/eventing/broker.md
  specs/eventing/channel.md
  specs/eventing/data-plane.md
  specs/eventing/helper.md
  specs/eventing/images/broker-trigger-overview.svg
  specs/eventing/images/resource-types-overview.svg
  specs/eventing/interfaces.md
  specs/eventing/motivation.md
  specs/eventing/overview.md
  specs/eventing/sources.md
  specs/eventing/spec.md
Labels: approved, cla: yes, lgtm, size/XXL

#8 trigger does not default to "default" broker on v1
  specs/eventing/broker.md
Labels: approved, cla: yes, lgtm, size/XS

#7 Serving specs
  specs/serving/README.md
  specs/serving/errors.md
  specs/serving/images/object_model.png
  specs/serving/knative-api-specification-1.0.md
  specs/serving/motivation.md
  specs/serving/normative_examples.md
  specs/serving/overview.md
  specs/serving/runtime-contract.md
Labels: approved, cla: yes, lgtm, size/XXL

#10 Remove pointer files
  specs/serving/errors.md
  specs/serving/normative_examples.md
Labels: approved, cla: yes, lgtm, size/S

#14 Add the KTC to approvers
  OWNERS
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#13 relax the malformed CE event to 4XX instead of only 415
  specs/eventing/broker.md
Labels: approved, cla: yes, lgtm, size/XS
