Repository knative/specs, pull requests merged in 2022-03, with the labels that each got.

#88 [Serving] Adds instructions for running conformance tests
  docs/conformance_procedure.md
  docs/examples/serving/cloud_run.md
  docs/run_serving_tests.md
Labels: lgtm, size/L, approved

#73 Include additional Container[*].SecurityContext properties
  specs/serving/knative-api-specification-1.0.md
  specs/serving/runtime-contract.md
Labels: cla: yes, lgtm, size/M, approved, needs-TMC-review

#93 Adding code of conduct to reference knative/community's CoC
  CODE-OF-CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: size/XS, lgtm, approved
